apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp
  labels:
    app: backapp
    training: block4
    optional: backapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backapp
      training: block4
      optional: backapp
  template:
    metadata:
      labels:
        app: backapp
        training: block4
        optional: backapp
    spec:
      containers:
      - name: backapp
        image: quay.io/drsylent/cubix/block3/homework-backapp:springboot3
        ports:
        - containerPort: 8080
          name: web
